config/routes.rb
Rails.application.routes.draw do

  root to: "bienvenido#index"

  resources :questions do
    resources :answers
  end


  devise_for :users, :skip => [:registrations]
  as :user do
  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
  put 'users' => 'devise/registrations#update', :as => 'user_registration'
  get '/users/sign_out' => 'devise/sessions#destroy'
end

  #CRUD USERS
  get '/users', to: 'users#index', as: 'users'
  get '/users/nuevo', to: 'users#nuevo' #new
  get '/users/:id', to: 'users#mostrar', as: 'user' #show
  post '/users', to: 'users#crear', as: 'crear_user'
  get 'users/:id/editar', to: 'users#editar', as: 'editar_user'
  put 'users/:id', to: 'users#update'
  patch 'users/:id', to: 'users#update'
  delete 'users/:id', to: 'users#eliminar'

  #CRUD AGENDA

  get '/agendas', to: 'agendas#index', as: 'agendas'
  get '/agendas/nuevo', to: 'agendas#nuevo' #new
  get '/agendas/:id', to: 'agendas#mostrar', as: 'agenda' #show
  post '/agendas', to: 'agendas#crear', as: 'crear_agenda'
  get 'agendas/:id/editar', to: 'agendas#editar', as: 'editar_agenda'
  put 'agendas/:id', to: 'agendas#update'
  patch 'agendas/:id', to: 'agendas#update'
  delete 'agendas/:id', to: 'agendas#eliminar'


  #CRUD PAGO

  get '/pagos', to: 'pagos#index', as: 'pagos'
  get 'pagos/buscar'
  get '/pagos/pdf/:id', to: 'pagos#show'
  get '/pagos/nuevo', to: 'pagos#nuevo' #new
  get '/pagos/:id', to: 'pagos#mostrar', as: 'pago' #show
  post '/pagos', to: 'pagos#crear', as: 'crear_pago'
  get 'pagos/:id/editar', to: 'pagos#editar', as: 'editar_pago'
  put 'pagos/:id', to: 'pagos#update'
  patch 'pagos/:id', to: 'pagos#update'
  delete 'pagos/:id', to: 'pagos#eliminar'


  #CRUD ESTUDIANTE

  get '/estudiantes', to: 'estudiantes#index', as: 'estudiantes'
  get 'estudiantes/nuevo', to: 'estudiantes#nuevo' #new
  get '/estudiantes/:id', to: 'estudiantes#mostrar', as: 'estudiante' #show
  post '/estudiantes', to: 'estudiantes#crear', as: 'crear_estudiante'
  get 'estudiantes/:id/editar', to: 'estudiantes#editar', as: 'editar_estudiante'
  put 'estudiantes/:id', to: 'estudiantes#update'
  patch 'estudiantes/:id', to: 'estudiantes#update'
  delete 'estudiantes/:id', to: 'estudiantes#eliminar'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pago.rb
class Pago < ApplicationRecord
  belongs_to :tipo_pago #pago puede tener asociado un tipo de pago
  belongs_to :estado #pago puede tener asociado uno estado
  has_many :user #pago puede estar asociado a un usuario
  belongs_to :estudiante #pago puede estar asociado a un estudiante

  validates :valor , presence: {message: 'ingrese un valor'}, numericality: { only_integer: true, message: 'tiene que ser numérico' }
  validates :abono , presence: {message: 'ingrese el abono'}, numericality: { only_integer: true, message: 'tiene que ser numérico' }
  validates :fecha_pago , presence: { message: 'Ingrese una fecha de pago'}
  validates :tipo_pago_id , presence: { message: 'Seleccione tipo de pago'}
  validates :estado_id , presence: { message: 'Seleccione estado de pago'}
  #validates :user_id , presence: { message: 'Seleccione al apoderado'}
  validates :estudiante_id , presence: { message: 'Seleccione al estudiante'}
  #validate :fecha_de_pago
  #validate :positivo
  #validate :validapago
  validate :abonomenorvalor
  validate :valorcero
  validate :abonocero
  before_save :resta

  def fecha_de_pago
    if !fecha_pago.blank? and fecha_pago < Date.today
      errors.add(:fecha, "ingresaste fecha que ya pasó")
    end
  end

  def abonocero
      if abono == 0
        errors.add(:abono, "tiene que ser mayor cero")
    end
  end

  def valorcero
    if valor == 0
      errors.add(:valor, "tiene que ser mayor a cero")
    end
  end

  def abonomenorvalor
    if abono > valor
      errors.add(:abono, "tiene que ser menor que valor")
    end
  end

  def resta
    self.saldo = self.valor-self.abono
  end

end

app/controllers/pagos_controller.rb
class PagosController < ApplicationController
  load_and_authorize_resource
  before_action :set_pago, only: [:mostrar,:editar,:update]

  def index
    #@pagos = Pago.search(params[:search])
    @pagos = Pago.order("fecha_pago DESC")
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template: 'pagos/listapagos', pdf: 'Listapagos', layout: 'lista.html'}
    end
  end

  def buscar
     @pagos = @pagos.where("estudiante_id = ?", params[:estudiante_id])
     @id_estudiante = params[:estudiante_id]
  end

  def show
    @pagos = Pago.where("estudiante_id = ?", params[:id])
    render template: 'pagos/buscapagos2.pdf', pdf: 'listapagos2', layout: 'lista.html'
  end

  def mostrar

  end

  #def eliminar
 #   @pago.destroy
    #respond_to do |format|
    #  format.html {redirect_to pagos_path, notice: 'eliminado'}
    #end
  #end

  def update
    @pago = Pago.find(params[:id])
      if @pago.update(pago_params)
        #redirect_to pago_path(@pago), notice: 'Se Actualizaron los datos'
        redirect_to "/pagos", notice: 'Se Actualizaron los datos'
      else
        render :editar
      end
  end

  def editar

    end

  def nuevo
    @pago=Pago.new
  end

  def crear
    @pago= Pago.new(pago_params)
    #@pago.saldo = @pago.valor - @pago.abono
    if @pago.abono != nil and @pago.valor != nil
      respond_to do |format|
        if @pago.save
          #format.html {redirect_to pago_path(@pago), notice: 'Se agrega el pago'}
          format.html {redirect_to "/pagos", notice: 'Se agrega el pago'}
        else
          format.html {render :nuevo}
        end
      end
    else
    @pago.abono = 0
    @pago.valor = 0
    respond_to do |format|
      if @pago.save
        #format.html {redirect_to pago_path(@pago), notice: 'Se agrega el pago'}
        format.html {redirect_to "/pagos", notice: 'Se agrega el pago'}
      else
        format.html {render :nuevo}
      end
    end
  end
  end

    private

    def pago_params
      params.require(:pago).permit(:valor,:fecha_pago, :saldo, :abono, :estudiante_id, :user_id,:tipo_pago_id, :estado_id)
      #jamas nunca poner ID en strongs paramas
      #tampoco updated_at  created_at
    end

    def set_pago
      @pago = Pago.find(params[:id])
    end
  end

app/helpers/pagos_helper.rb
module PagosHelper
end

app/views/pagos/_formulariopagos.html.erb
<div class="container-form">
<%= form_for(@pago, :html => {:role => 'form'}) do |f| %>
  <% if @pago.errors.any? %>
  <div class="alert alert-info">
    <%= pluralize(@pago.errors.count, "Errores") %>
  </div>
  <div class="alert alert-danger">
    <% @pago.errors.full_messages.each do |error| %>
      <%= error %><br>
    <% end %>
  </div>
  <% end %>

  <h1>Registro de Pagos</h1>

  <div class="field"><br>
    <%= f.label :tipo_de_pago %>
    <%= f.select('tipo_pago_id',
               TipoPago.all.collect { |c| [c.descripcion, c.id] }) %>
  </div>


  <div class="field"><br>
    <%= f.label :estudiante,autofocus: true %>
    <%= f.select('estudiante_id',
                 Estudiante.all.collect {|c| [c.nombreuno + " "+ c.apellidouno + " "+ c.apellidodos, c.id]}) %>
  </div>

  <div class="field"><br>
    <%= f.label :valor, autofocus: true, placeholder: "Valor" %>
    <%= f.text_field :valor %>
  </div>

  <div class="field"><br>
    <%= f.label :abono,autofocus: true, placeholder: "Abono" %>
    <%= f.text_field :abono %>
  </div>

  <div class="field"><br>
    <%= f.label :fecha_pago %>
    <%= f.date_field :fecha_pago %>
  </div>


  <div class="field"><br>
    <%= f.label :estado %>
    <%= f.select('estado_id',
               Estado.all.collect { |c| [c.descripcion, c.id] }) %>
  </div>

<div class="actions"><br>
  <%= f.submit 'Guardar Pago', class:"btn btn-success"%>
</div>
</div>
<% end %>
</div>

app/views/pagos/buscapagos2.pdf.erb
<center><h1> Pagos de Sala Cuna y Jardín Infatil </h1></center>
<table class="table">
  <thead>
  <tr>
    <th style="width: 200px; text-align: center;">Estudiante</th>
    <th style="width: 200px; text-align: center;">Valor</th>
    <th style="width: 200px; text-align: center;">Abono</th>
    <th style="width: 200px; text-align: center;">Saldo</th>
    <th style="width: 200px; text-align: center;">Fecha pago</th>
    <th style="width: 200px; text-align: center;">Fecha ingreso</th>
    <th style="width: 200px; text-align: center;">Estado</th>
    <th style="width: 200px; text-align: center;">Tipo de pago </th>
  </tr>
  </thead>
  <tbody>
  <% @pagos.each do |pago| %>
    <tr>
      <td style="text-align: center;"><%= pago.estudiante.nombreuno %> <%= pago.estudiante.apellidouno%></td>
      <td style="text-align: center;"><%= pago.valor %></td>
      <td style="text-align: center;"><%= pago.abono %></td>
      <td style="text-align: center;"><%= pago.saldo %></td>
      <td style="text-align: center;"><%= pago.fecha_pago.strftime("%d-%m-%y")  %></td>
      <td style="text-align: center;"><%= pago.created_at.strftime("%d-%m-%y")  %></td>
      <td style="text-align: center;"><%= pago.estado.descripcion %></td>
      <td style="text-align: center;"><%= pago.tipo_pago.descripcion %></td>
    </tr>
    <%end%>
  </tbody>
</table>

app/views/pagos/buscar.html.erb
<!DOCTYPE html>
<body>
<head>
</head>
<body></body>
<div class="container-form">
  <h1>Listado de Pagos</h1><br>
<div class="derecha">
    <h1>
      <a href="pdf/<%= @id_estudiante %>" target="_blank">
        <i class="fas fa-file-pdf"></i>
      </a>

    <br></h1>
</div>

 <%=form_tag("buscar", method: :get) do %>
  <div class="form-group, col-3">
    <%= select_tag 'estudiante_id', options_for_select(Estudiante.all.collect{|u| [u.nombreuno + " "+ u.apellidouno, u.id]}), class: "form-control" %>
  </div><br>
  <%= submit_tag "Buscar", nombreuno: nil, class: "btn btn-primary btn-md" %>
  <%= link_to "Volver", "/pagos" , class:"btn btn-secondary"%>
<% end %><br>
<table class="table table-condensed table-bordered">
  <thead>
  <tr>
    <th>Estudiante</th>
    <th>Valor</th>
    <th>Abono</th>
    <th>Saldo</th>
    <th>Fecha pago</th>
    <th>Estado</th>
    <th>Tipo pago</th>
    <th colspan="3">Opciones</th>
  </tr>
  </thead>
  <tbody>
  <% @pagos.each do |pago| %>
    <tr>
      <td><%= pago.estudiante.nombreuno%> <%= pago.estudiante.apellidouno %></td>
      <td><%= pago.valor %></td>
      <td><%= pago.abono %></td>
      <td><%= pago.saldo%></td>
      <td><%= pago.fecha_pago %></td>
      <td>
        <%if pago.estado.descripcion ==  'Pendiente'%>
        <p class="text-danger"><%= pago.estado.descripcion %></p>
          <%end %>
        <%if pago.estado.descripcion ==  'Pagado'%>
          <p class="text-success"><%= pago.estado.descripcion %></p>
        <%end %>
      </td>
      <td><%= pago.tipo_pago.descripcion %></td>
      <td><%= link_to 'Mostrar', pago_url(pago), class: "btn btn-info" %></td>
      <td><%= link_to 'Editar', editar_pago_url(pago), class: "btn btn-warning" %></td>
    </tr>
    <%end%>
  </tbody>
</table>
</div>
</html>

app/views/pagos/editar.html.erb
<%= render 'formulariopagos' %>

app/views/pagos/index.html.erb
<!DOCTYPE html>
<body>
<head>
</head>
<body></body>
<div class="container-form">
  <h1>Listado de Pagos</h1><br>
<div class="derecha">
    <h1><a href="/pagos.pdf"><i class="fas fa-file-pdf"></i></a> <a href="pagos/nuevo" class="btn btn-success btn-lg btn-primary" role="button" aria-pressed="true">Agregar pago</a><br></h1>
</div>
<div class="col-3">
<%= form_tag("pagos/buscar", method: :get) do %>
  <div class="form-group">
    <%= select_tag 'estudiante_id', options_for_select(Estudiante.all.collect{|u| [u.nombreuno + " "+ u.apellidouno, u.id]}), class: "form-control" %>
  </div>
  <%= submit_tag "Buscar", name: nil, class: "btn btn-primary btn-md" %>
<% end %>
</div>
<table class="table table-condensed table-bordered">
  <thead>
  <tr>
    <th>Estudiante</th>
    <th>Valor</th>
    <th>Abono</th>
    <th>Saldo</th>
    <th>Fecha pago</th>
    <th>Fecha de ingreso</th>
    <th>Estado</th>
    <th>Tipo pago</th>
    <th colspan="3">Opciones</th>
  </tr>
  </thead>
  <tbody>
  <% @pagos.each do |pago| %>
    <tr>
      <td><%= pago.estudiante.nombreuno%> <%= pago.estudiante.apellidouno %></td>
      <td><%= pago.valor %></td>
      <td><%= pago.abono %></td>
      <td><%= pago.saldo%></td>
      <td><%= pago.fecha_pago.strftime("%d-%m-%y") %></td>
      <td><%= pago.created_at.strftime("%d-%m-%y") %></td>
      <td>
        <%if pago.estado.descripcion ==  'Pendiente'%>
        <p class="text-danger"><%= pago.estado.descripcion %></p>
          <%end %>
        <%if pago.estado.descripcion ==  'Pagado'%>
          <p class="text-success"><%= pago.estado.descripcion %></p>
        <%end %>
      </td>
      <td><%= pago.tipo_pago.descripcion %></td>
      <td><%= link_to 'Mostrar', pago_url(pago), class: "btn btn-info" %></td>
      <td><%= link_to 'Editar', editar_pago_url(pago), class: "btn btn-warning" %></td>
    </tr>
    <%end%>
  </tbody>
</table>
</div>
</body>
</html>

app/views/pagos/listapagos.pdf.erb
<center><h1> Pagos de Sala Cuna y Jardín Infatil </h1></center>
<table class="table">
  <thead>
  <tr>
    <th style="width: 200px; text-align: center;">Estudiante</th>
    <th style="width: 200px; text-align: center;">Valor</th>
    <th style="width: 200px; text-align: center;">Abono</th>
    <th style="width: 200px; text-align: center;">Saldo</th>
    <th style="width: 200px; text-align: center;">Fecha pago</th>
    <th style="width: 200px; text-align: center;">Fecha ingreso</th>
    <th style="width: 200px; text-align: center;">Estado</th>
    <th style="width: 200px; text-align: center;">Tipo de pago </th>
  </tr>
  </thead>
  <tbody>
  <% @pagos.each do |pago| %>
    <tr>
      <td style="text-align: center;"><%= pago.estudiante.nombreuno %> <%= pago.estudiante.apellidouno%></td>
      <td style="text-align: center;"><%= pago.valor %></td>
      <td style="text-align: center;"><%= pago.abono %></td>
      <td style="text-align: center;"><%= pago.saldo %></td>
      <td style="text-align: center;"><%= pago.fecha_pago.strftime("%d-%m-%y")  %></td>
      <td style="text-align: center;"><%= pago.created_at.strftime("%d-%m-%y")  %></td>
      <td style="text-align: center;"><%= pago.estado.descripcion %></td>
      <td style="text-align: center;"><%= pago.tipo_pago.descripcion %></td>
    </tr>
    <%end%>
  </tbody>
</table>

app/views/pagos/mostrar.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <meta charset="utf-8">
</head>
<body>
  <div class="container-form">
  <h1>Estudiante: <%= @pago.estudiante.nombreuno%> <%= @pago.estudiante.apellidouno%><h1>
<h1>Valor: <%= @pago.valor %></h1>
<h1>Saldo: <%= @pago.saldo %></h1>
<h1>Abono: <%= @pago.abono %></h1>
<h1>Fecha: <%= @pago.fecha_pago%></h1>
<h1>Estado: <%= @pago.estado.descripcion %></h1>
<h1>Tipo de pago: <%= @pago.tipo_pago.descripcion %></h1>

<a href="/pagos" class="btn btn-secondary btn-lg" role="button" aria-pressed="true">Volver</a></h1>
</div>
</body>
</html>

app/views/pagos/nuevo.html.erb
<%= render 'formulariopagos' %>