config/routes.rb
Rails.application.routes.draw do

  root to: "bienvenido#index"

  resources :questions do
    resources :answers
  end


  devise_for :users, :skip => [:registrations]
  as :user do
  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
  put 'users' => 'devise/registrations#update', :as => 'user_registration'
  get '/users/sign_out' => 'devise/sessions#destroy'
end

  #CRUD USERS
  get '/users', to: 'users#index', as: 'users'
  get '/users/nuevo', to: 'users#nuevo' #new
  get '/users/:id', to: 'users#mostrar', as: 'user' #show
  post '/users', to: 'users#crear', as: 'crear_user'
  get 'users/:id/editar', to: 'users#editar', as: 'editar_user'
  put 'users/:id', to: 'users#update'
  patch 'users/:id', to: 'users#update'
  delete 'users/:id', to: 'users#eliminar'

  #CRUD AGENDA

  get '/agendas', to: 'agendas#index', as: 'agendas'
  get '/agendas/nuevo', to: 'agendas#nuevo' #new
  get '/agendas/:id', to: 'agendas#mostrar', as: 'agenda' #show
  post '/agendas', to: 'agendas#crear', as: 'crear_agenda'
  get 'agendas/:id/editar', to: 'agendas#editar', as: 'editar_agenda'
  put 'agendas/:id', to: 'agendas#update'
  patch 'agendas/:id', to: 'agendas#update'
  delete 'agendas/:id', to: 'agendas#eliminar'


  #CRUD PAGO

  get '/pagos', to: 'pagos#index', as: 'pagos'
  get 'pagos/buscar'
  get '/pagos/pdf/:id', to: 'pagos#show'
  get '/pagos/nuevo', to: 'pagos#nuevo' #new
  get '/pagos/:id', to: 'pagos#mostrar', as: 'pago' #show
  post '/pagos', to: 'pagos#crear', as: 'crear_pago'
  get 'pagos/:id/editar', to: 'pagos#editar', as: 'editar_pago'
  put 'pagos/:id', to: 'pagos#update'
  patch 'pagos/:id', to: 'pagos#update'
  delete 'pagos/:id', to: 'pagos#eliminar'


  #CRUD ESTUDIANTE

  get '/estudiantes', to: 'estudiantes#index', as: 'estudiantes'
  get 'estudiantes/nuevo', to: 'estudiantes#nuevo' #new
  get '/estudiantes/:id', to: 'estudiantes#mostrar', as: 'estudiante' #show
  post '/estudiantes', to: 'estudiantes#crear', as: 'crear_estudiante'
  get 'estudiantes/:id/editar', to: 'estudiantes#editar', as: 'editar_estudiante'
  put 'estudiantes/:id', to: 'estudiantes#update'
  patch 'estudiantes/:id', to: 'estudiantes#update'
  delete 'estudiantes/:id', to: 'estudiantes#eliminar'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :estudiantes
  has_many :pagos
  has_many :agendas
  belongs_to :tipo_usuario
  belongs_to :comuna, optional: true
  has_many :questions
  has_many :answers

  validates :nombreuno , presence:  { message: 'Ingrese el primer nombre '} , length: {in: 3..20, message:'El nombre debe ser de mínimo largo 3'}, format: {with: /\A[a-zA-Z]+\z/,
    message: "Se permiten solo letras en los nombres"}
  validates :apellidouno , presence: { message: 'Ingrese el primer apellido'}, length: {in: 3..20, message:'El apellido debe ser de mínimo largo 3'}, format: {with: /\A[a-zA-Z]+\z/,
    message: "Se permiten solo letras en los apellidos"}
    validates :nombredos , presence:  { message: 'Ingrese el segundo nombre '} , length: {in: 3..20, message:'El nombre debe ser de mínimo largo 3'}, format: {with: /\A[a-zA-Z]+\z/,
    message: "Se permiten solo letras en los nombres"}
  validates :apellidodos , presence: { message: 'Ingrese el segundo apellido'}, length: {in: 3..20, message:'El apellido debe ser de mínimo largo 3'}, format: {with: /\A[a-zA-Z]+\z/,
    message: "Se permiten solo letras en los apellidos"}
  VALID_RUT_REGEX = /\A(\d{1,3})\.(\d{1,3})\.(\d{1,3})\-(k|\d{1})\Z/i
  validates :rut , presence: { message: 'Ingrese un rut'}, uniqueness: true, format: {with: VALID_RUT_REGEX}
  validates :comuna_id , presence: { message: 'Seleccione alguna comuna'}
  validates :fecha_nacimiento , presence: {message: 'Ingrese la fecha de nacimiento'}
  validates :celular, presence: {message: 'Ingrese celular'}, length: {is: 9, message:'Largo debe ser 9'}
  validate :fecha_de_nacimiento_debe_ser_en_pasado
  validate :edadminima
  validate :active_for_authentication?


def fecha_de_nacimiento_debe_ser_en_pasado
    if fecha_nacimiento.present? && fecha_nacimiento >= Date.today
      errors.add(:fecha_nacimiento, "debe ser anterior a la fecha de hoy")
    end
end


  def edadminima
     if fecha_nacimiento.present? && fecha_nacimiento >= 18.year.ago
          errors.add(:fecha_nacimiento, "debe ser mayor de 18 años")
     end
  end

  def active_for_authentication?
    super && self.estado
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: [:mostrar,:eliminar,:editar,:update]

  def index
    @users = @users.where("nombreuno ILIKE ?", "%#{params[:nombreuno]}%")
    @users = @users.where("apellidouno ILIKE ?", "%#{params[:apellidouno]}%")
    respond_to do |format|
      format.html
      format.json
      end
  end

  def mostrar
  end

  def eliminar
    #@user.destroy
    @user.estado = false
    @user.save
    respond_to do |format|
      format.html {redirect_to users_path, notice: 'Apoderado no regular'}
    end
  end

  def update
      if @user.update(user_params)
        respond_to do |format|
        format.html {redirect_to "/users", notice: 'Se Actualizaron los datos'}
      end
      else
        render :editar
      end
  end

  def editar
  end

  def nuevo
    @user= User.new
  end

  def crear
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html {redirect_to "/users", notice: 'Se Registro Usuario'}
      else
        format.html {render :nuevo}
      end
    end
  end


  private

  def user_params
    params.require(:user).permit(:nombreuno, :nombredos, :apellidouno, :apellidodos, :rut, :fecha_nacimiento, :direccion, :comuna_id, :celular, :email, :password, :password_confirmation, :tipo_usuario_id, :estado)
    #jamas nunca poner ID en strongs paramas
    #tampoco updated_at  created_at
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_formulariousers.html.erb
<div class="container-form">
<%= form_for(@user, :html => {:role => 'form'}) do |f| %>
  <% if @user.errors.any? %>
  <div class="alert alert-info">
    <%= pluralize(@user.errors.count, "Errores") %>
  </div>
  <div class="alert alert-danger">
    <% @user.errors.full_messages.each do |error| %>
      <%= error %><br>
    <% end %>
  </div>
    <% end %>

<div class="form">
  <h1 class="text-center"> Registro de Usuarios</h1>

  <div class="row">

  <div class="col">
  <div class="field">
    <%= f.label :primer_nombre %><br/>
    <%= f.text_field :nombreuno, autofocus: true, class: "form-control", placeholder: "Primer nombre" %>
  </div><br>
</div>

  <div class="col">
  <div class="field">
    <%= f.label :segundo_nombre %><br/>
    <%= f.text_field :nombredos, autofocus: true, class: "form-control", placeholder: "Segundo nombre" %>
  </div>
  </div>
</div>

<div class="row">

  <div class="col">
  <div class="field">
    <%= f.label :primer_apellido %><br/>
    <%= f.text_field :apellidouno, autofocus: true, class: "form-control", placeholder: "Primer apellido" %>
  </div><br>
</div>

  <div class="col">
  <div class="field">
    <%= f.label :segundo_apellido %><br/>
    <%= f.text_field :apellidodos, autofocus: true, class: "form-control", placeholder: "Segundo apellido" %>
  </div>
  </div>
</div>
  <div class="row">
    <div class="col">
  <div class="field">
    <%= f.label :rut %><br/>
    <%= f.text_field :rut, autofocus: true, class:"form-control", placeholder: "11.111.111-1" %>
  </div><br>
</div>
  <div class="col">
  <div class="field">
    <%= f.label :fecha_nacimiento %><br/>
    <%= f.date_field :fecha_nacimiento, autofocus: true, class:"form-control" %>
  </div>
</div>
  <div class="col">
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control", placeholder: "Email" %>
  </div>
</div>
</div>
<div class="row">
  <div class="col">
  <div class="field">
    <%= f.label :Contraseña %>
    <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br/>
    <%= f.password_field :password, autocomplete: "off", class:"form-control" , placeholder:"Contraseña"%>
  </div><br>
</div>
<div class="col">
  <div class="field">
    <%= f.label :Confirmar_contraseña %><br/>
    <%= f.password_field :password_confirmation, autocomplete: "off", class:"form-control", placeholder:"Confirmar contraseña" %>
  </div>
</div>
</div>
<div class="row">
  <div class="col">
  <div class="field">
    <%= f.label :direccion %><br/>
    <%= f.text_field :direccion, autofocus: true , class: "form-control", placeholder: "Direccion"%>
  </div><br/>
</div>
<div class="col">
<div class="field">
  <%= f.label :comuna %><br>
  <%= f.select('comuna_id',
               Comuna.all.collect {|c| [c.descripcion, c.id]}, class: "form-control") %>
</div>
  </div>
  <div class="col">
<div class="field">
  <%= f.label :celular %><br/>
  <%= f.text_field :celular, autofocus: true, class: "form-control", placeholder:"Celular" %>
</div>
</div>
</div>
<div class="field">
  <%= f.label :Tipo_de_usuario %>
  <%= f.select('tipo_usuario_id',
               TipoUsuario.all.collect {|c| [c.descripcion, c.id]}, class: "form-control") %>
</div>

  <div class="actions">
    <%= f.submit "Guardar Usuario" ,class:"btn btn-success"%>
  </div>
<% end %>
</div>
</div>

app/views/users/editar.html.erb
<div class="container-form">
<%= form_for(@user, :html => {:role => 'form'}) do |f| %>
  <% if @user.errors.any? %>
  <div class="alert alert-info">
    <%= pluralize(@user.errors.count, "Errores") %>
  </div>
  <div class="alert alert-danger">
    <% @user.errors.full_messages.each do |error| %>
      <%= error %><br>
    <% end %>
  </div>
    <% end %>

<div class="form">
  <h1 class="text-center"> Registro de Usuarios</h1>

  <div class="row">

  <div class="col">
  <div class="field">
    <%= f.label :primer_nombre %><br/>
    <%= f.text_field :nombreuno, autofocus: true, class: "form-control", placeholder: "Primer nombre" %>
  </div><br>
</div>

  <div class="col">
  <div class="field">
    <%= f.label :primer_apellido %><br/>
    <%= f.text_field :apellidouno, autofocus: true, class: "form-control", placeholder: "Primer apellido" %>
  </div>
  </div>
</div>

<div class="row">

  <div class="col">
  <div class="field">
    <%= f.label :segundo_nombre %><br/>
    <%= f.text_field :nombredos, autofocus: true, class: "form-control", placeholder: "Primer nombre" %>
  </div><br>
</div>

  <div class="col">
  <div class="field">
    <%= f.label :segundo_apellido %><br/>
    <%= f.text_field :apellidodos, autofocus: true, class: "form-control", placeholder: "Primer apellido" %>
  </div>
  </div>
</div>
  <div class="row">
    <div class="col">
  <div class="field">
    <%= f.label :rut %><br/>
    <%= f.text_field :rut, autofocus: true, class:"form-control", placeholder: "Rut" %>
  </div><br>
</div>
  <div class="col">
  <div class="field">
    <%= f.label :fecha_nacimiento %><br/>
    <%= f.date_field :fecha_nacimiento, autofocus: true, class:"form-control" %>
  </div>
</div>
  <div class="col">
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control", placeholder: "Email" %>
  </div>
</div>
</div>

<div class="row">
  <div class="col">
  <div class="field">
    <%= f.label :direccion %><br/>
    <%= f.text_field :direccion, autofocus: true , class: "form-control", placeholder: "Direccion"%>
  </div><br/>
</div>
<div class="col">
<div class="field">
  <%= f.label :comuna %><br>
  <%= f.select('comuna_id',
               Comuna.all.collect {|c| [c.descripcion, c.id]}, class: "form-control") %>
</div>
  </div>
  <div class="col">
<div class="field">
  <%= f.label :celular %><br/>
  <%= f.text_field :celular, autofocus: true, class: "form-control", placeholder:"Celular" %>
</div>
</div>
</div>

<div class="row">
  <div class="col">
<div class="field">
  <%= f.label :Tipo_de_usuario %>
  <%= f.select('tipo_usuario_id',
               TipoUsuario.all.collect {|c| [c.descripcion, c.id]}, class: "form-control") %>
</div>
</div>

<div class="col">

 <div class="field">
    <%= f.label "Estado" %> <br />
    <%= f.check_box :estado %> <br />
</div>
</div>

 </div>
  <div class="actions">
    <%= f.submit "Guardar Usuario" ,class:"btn btn-success"%>
  </div>
<% end %>
</div>
</div>

app/views/users/index.html.erb
<!DOCTYPE html>
<body>
<head>
</head>

<body></body>
<div class="container-form">
  <h1>Listado de Usuarios</h1><br>
  <div class="derecha">
    <h1><a href="/users/nuevo" class="btn btn-success btn-lg" role="button" aria-pressed="true">Nuevo</a></h1>
</div>
<%= form_tag users_path, method: :get do %>
  <div class="form-group">
    <%= text_field_tag :nombreuno, params[:nombreuno], class: "form-control-3", placeholder: "primer nombre" %>
  </div>
  <div class="form-group">
    <%= text_field_tag :apellidouno, params[:apellidouno], class: "form-control-3", placeholder: "primer apellido" %>
  </div>
  <%= submit_tag "Buscar", name: nil, class: "btn btn-primary btn-md" %>
  <%= link_to "Volver", "/users" , class:"btn btn-secondary"%>
<% end %>
<table class="table table-condensed table-bordered">
  <thead>
  <tr>
    <th>Nombre</th>
    <th>Rut</th>
    <th>Tipo de usuario</th>
    <th>Estado</th>
    <th colspan="3">Opciones</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.nombreuno %> <%= user.apellidouno %></td>
      <td><%= user.rut %></td>
      <td><%= user.tipo_usuario.descripcion%></td>
      <td>
      <% if user.estado == false %>
      <p class="text-danger"><%= user.estado %></p>
      <% end %>

      <% if user.estado == true %>
      <p class="text-success"><%= user.estado %></p>
      <% end %>

      </td>
      <td><%= link_to 'Mostrar', user_url(user), class: "btn btn-info" %></td>
      <td><%= link_to 'Editar', editar_user_url(user), class: "btn btn-warning" %></td>
      <% if user.estado == true %>
      <td><%= link_to 'Cambiar estado', user_path(user), class: "btn btn-danger",
                      method: :delete, data: {confirm: '¿Estas seguro?'} %></td>
                      <% end %>
    </tr>
    <%end%>

  </tbody>
</table>
</div>
</body>
</html>

app/views/users/mostrar.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <meta charset="utf-8">
</head>
<body>
  <div class="container-form">
  <h1>Nombre: <%= @user.nombreuno %> <%= @user.apellidouno %></h1>
  <h1>Rut: <%= @user.rut %></h1>
  <h1>Fecha de Nacimiento: <%= @user.fecha_nacimiento %></h1>
  <h1>Direccion: <%= @user.direccion %></h1>
  <h1>Comuna: <%= @user.comuna.descripcion %></h1>
  <h1>Celular: <%= @user.celular %></h1>
  <h1>Tipo: <%= @user.tipo_usuario.descripcion %></h1>
  <a href="/users" class="btn btn-secondary btn-lg" role="button" aria-pressed="true">Volver</a></h1>
</div>
</body>
</html>

app/views/users/nuevo.html.erb
<%= render 'formulariousers' %>