config/routes.rb
Rails.application.routes.draw do

  root to: "bienvenido#index"

  resources :questions do
    resources :answers
  end


  devise_for :users, :skip => [:registrations]
  as :user do
  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
  put 'users' => 'devise/registrations#update', :as => 'user_registration'
  get '/users/sign_out' => 'devise/sessions#destroy'
end

  #CRUD USERS
  get '/users', to: 'users#index', as: 'users'
  get '/users/nuevo', to: 'users#nuevo' #new
  get '/users/:id', to: 'users#mostrar', as: 'user' #show
  post '/users', to: 'users#crear', as: 'crear_user'
  get 'users/:id/editar', to: 'users#editar', as: 'editar_user'
  put 'users/:id', to: 'users#update'
  patch 'users/:id', to: 'users#update'
  delete 'users/:id', to: 'users#eliminar'

  #CRUD AGENDA

  get '/agendas', to: 'agendas#index', as: 'agendas'
  get '/agendas/nuevo', to: 'agendas#nuevo' #new
  get '/agendas/:id', to: 'agendas#mostrar', as: 'agenda' #show
  post '/agendas', to: 'agendas#crear', as: 'crear_agenda'
  get 'agendas/:id/editar', to: 'agendas#editar', as: 'editar_agenda'
  put 'agendas/:id', to: 'agendas#update'
  patch 'agendas/:id', to: 'agendas#update'
  delete 'agendas/:id', to: 'agendas#eliminar'


  #CRUD PAGO

  get '/pagos', to: 'pagos#index', as: 'pagos'
  get 'pagos/buscar'
  get '/pagos/pdf/:id', to: 'pagos#show'
  get '/pagos/nuevo', to: 'pagos#nuevo' #new
  get '/pagos/:id', to: 'pagos#mostrar', as: 'pago' #show
  post '/pagos', to: 'pagos#crear', as: 'crear_pago'
  get 'pagos/:id/editar', to: 'pagos#editar', as: 'editar_pago'
  put 'pagos/:id', to: 'pagos#update'
  patch 'pagos/:id', to: 'pagos#update'
  delete 'pagos/:id', to: 'pagos#eliminar'


  #CRUD ESTUDIANTE

  get '/estudiantes', to: 'estudiantes#index', as: 'estudiantes'
  get 'estudiantes/nuevo', to: 'estudiantes#nuevo' #new
  get '/estudiantes/:id', to: 'estudiantes#mostrar', as: 'estudiante' #show
  post '/estudiantes', to: 'estudiantes#crear', as: 'crear_estudiante'
  get 'estudiantes/:id/editar', to: 'estudiantes#editar', as: 'editar_estudiante'
  put 'estudiantes/:id', to: 'estudiantes#update'
  patch 'estudiantes/:id', to: 'estudiantes#update'
  delete 'estudiantes/:id', to: 'estudiantes#eliminar'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/estudiante.rb
class Estudiante < ApplicationRecord
  has_many :pagos #un estudiante puede tener asociados muchos pagos
  has_many :agendas
  belongs_to :user #un estudiante puede tener asociado un usuario(apoderado)
  belongs_to :comuna #un estudiante puede tener asociado una comuna
  belongs_to :jornada #un estudiante puede ser asociada una jornada
  belongs_to :nivel_educacional #un estudiante puede ser asociado un nivel educacional

  validates :nombreuno , presence:  { message: 'Ingrese el primer nombre '} , length: {in: 3..20}, format: {with: /\A[a-zA-Z]+\z/,
    message: "Se permiten solo letras en los nombres"}
  validates :apellidouno , presence: { message: 'Ingrese el primer apellido'}, length: {in: 3..20}, format: {with: /\A[a-zA-Z]+\z/,
    message: "Se permiten solo letras en los apellidos"}
  validates :nombredos , presence:  { message: 'Ingrese el segundo nombre '} , length: {in: 3..20}, format: {with: /\A[a-zA-Z]+\z/,
    message: "Se permiten solo letras en los nombres"}
  validates :apellidodos , presence: { message: 'Ingrese el segundo apellido'}, length: {in: 3..20}, format: {with: /\A[a-zA-Z]+\z/,
    message: "Se permiten solo letras en los apellidos"}
  VALID_RUT_REGEX = /\A(\d{1,3})\.(\d{1,3})\.(\d{1,3})\-(k|\d{1})\Z/i
  validates :rut , presence: { message: 'Ingrese un rut'}, uniqueness: true, format: {with: VALID_RUT_REGEX}
  validates :direccion, presence: {message: 'Ingrese direccion'}
  validates :comuna_id , presence: { message: 'Seleccione alguna comuna'}
  validates :jornada_id , presence: { message: 'Selecciones alguna jornada'}
  validates :nivel_educacional_id , presence: { message: 'Seleccione algún nivel educacional'}
  validates :fecha_nacimiento , presence: {message: 'Ingrese la fecha de nacimiento'}
  validate :fecha_de_nacimiento_debe_ser_en_pasado
  validate :fechaminima


  def fecha_de_nacimiento_debe_ser_en_pasado
    if fecha_nacimiento.present? && fecha_nacimiento >= Date.today
      errors.add(:fecha_nacimiento, "debe ser anterior a la fecha de hoy")
    end
end

  def fechaminima
      if fecha_nacimiento.present? && fecha_nacimiento <= 4.year.ago
        errors.add(:fecha_nacimiento, "debe ser menor de 4 años  ")
    end
  end

  def self.search(search)
    if search
      where(["nombreuno LIKE ?","%#{search}%"])
    else
      all
    end
  end

end

app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController
  load_and_authorize_resource
  before_action :set_estudiante, only: [:mostrar,:eliminar,:editar,:update]

  def index
    @estudiantes = Estudiante.paginate(:page => params[:page], :per_page =>10)
      @estudiantes = @estudiantes.where("nombreuno ILIKE ?", "%#{params[:nombreuno]}%")
      @estudiantes = @estudiantes.where("apellidouno ILIKE ?", "%#{params[:apellidouno]}%")
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template: 'estudiantes/lista', pdf: 'Lista', layout: 'lista.html'}
      end
  end

  def mostrar
  end

  def eliminar
    #@estudiante.nombres ="eliminado"
    @estudiante.estado = false
    @estudiante.save
    #@estudiante.destroy
    respond_to do |format|
      #format.html {redirect_to estudiantes_path, notice: 'Estudiante no regular'}
      format.html {redirect_to "/estudiantes", notice: 'Estudiante no regular'}
    end
  end

  def update
     @estudiante = Estudiante.find(params[:id])
      if @estudiante.update(estudiante_params)
        #redirect_to estudiante_path(@estudiante), notice: 'Se Actualizaron los datos'
        redirect_to "/estudiantes", notice: 'Se Actualizaron los datos'
      else
        render :editar
      end
  end

  def editar
  end

  def nuevo
    @estudiante= Estudiante.new
  end

  def crear
    @estudiante = Estudiante.new(estudiante_params)
    respond_to do |format|
      if @estudiante.save
        format.html {redirect_to estudiante_path(@estudiante), notice: 'Se registra a estudiante'}
      else
        format.html {render :nuevo}
      end
    end
  end


  private

  def estudiante_params
    params.require(:estudiante).permit(:nombreuno, :nombredos, :apellidouno, :apellidodos, :rut, :fecha_nacimiento, :direccion, :comuna_id, :nivel_educacional_id, :jornada_id, :user_id, :estado)
    #jamas nunca poner ID en strongs paramas
    #tampoco updated_at  created_at
  end

  def set_estudiante
    @estudiante = Estudiante.find(params[:id])
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template: 'estudiantes/pdf', pdf: 'Pdf'}
  end

  end
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/views/estudiantes/_formulario.html.erb
<div class="container-form">
<%= form_for(@estudiante, :html => {:role => 'form'}) do |f| %>
  <% if @estudiante.errors.any? %>
  <div class="alert alert-info">
    <%= pluralize(@estudiante.errors.count, "Errores") %>
  </div>
  <div class="alert alert-danger">
    <% @estudiante.errors.full_messages.each do |error| %>
      <%= error %><br>

    <% end %>
    </div>
  <% end %>

<div class="form">
  <h1 class="text-center"> Registro de Estudiante</h1>
  <div class="row">
    <div class="col">
      <div class="form-group">
        <%= f.label :primer_nombre %>
        <%= f.text_field :nombreuno, class: "form-control", placeholder: "Primer nombre" %>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <%= f.label :segundo_nombre %>
        <%= f.text_field :nombredos, class: "form-control", placeholder: "Segundo nombre" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="form-group">
        <%= f.label :primer_apellido %>
        <%= f.text_field :apellidouno, class: "form-control", placeholder: "Primer apellido" %>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <%= f.label :segundo_apellido %>
        <%= f.text_field :apellidodos, class: "form-control", placeholder: "Segundo apellido" %>
      </div>
    </div>
  </div>

  <div class="row">

    <div class="col">
      <div class="form-group">
        <%= f.label :rut %>
        <%= f.text_field :rut, class: "form-control", placeholder: "11.111.111-1" %>
      </div>
    </div>


    <div class="col">
      <div class="form-group">
        <%= f.label :fecha_nacimiento %>
        <%= f.date_field :fecha_nacimiento, class: "form-control ", placeholder: "Fecha de Nacimiento"%>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <%= f.label :direccion %>
        <%= f.text_field :direccion, class: "form-control", placeholder: "Direccion" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">

        <%= f.label :comuna %><br>
        <%= f.select('comuna_id',
                     Comuna.all.collect {|c| [c.descripcion, c.id]}, class: "form-control") %>

    </div>
    <div class="col">
        <%= f.label :nivel_educacional %><br>
        <%= f.select('nivel_educacional_id',
                     NivelEducacional.all.collect {|c| [c.descripcion, c.id]}) %>
    </div>

    <div class="col">
      <%= f.label :jornada %><br>
      <%= f.select('jornada_id',
                   Jornada.all.collect {|c| [c.descripcion, c.id]}) %>
    </div>

    <div class="col">
      <%= f.label :apoderado%><br>
      <%= f.select('user_id',
                   User.all.collect {|c| [c.nombreuno + " "+ c.apellidouno + " "+ c.apellidodos, c.id]}) %>
    </div>


    <div class="field">
    <%= f.label "Estado" %> <br />
    <%= f.check_box :estado %> <br />
</div>
  </div>
  <div class="btn">
  <%= f.submit 'Guardar Estudiante', class:"btn btn-success"%>
  </div>
<% end %>
</div>
</div>

app/views/estudiantes/editar.html.erb
<%= render 'formulario' %>

app/views/estudiantes/index.html.erb
<!DOCTYPE html>
<body>
<head>
</head>

<body></body>
<div class="container-form">
  <h1>Listado de Estudiantes</h1><br>
  <div class="derecha">
    <h1><a href="/estudiantes.pdf"><i class="fas fa-file-pdf"></i></a>
      <% if can? :crear, @estudiantes %>
      <%= link_to 'Nuevo', estudiantes_nuevo_url, class:"btn btn-success" %>
      <% end %>
    </h1>
</div>

<%= form_tag estudiantes_path, method: :get do %>
  <div class="form-group">
    <%= text_field_tag :nombreuno, params[:nombreuno], class: "form-control-3", placeholder: "primer nombre" %>
  </div>
  <div class="form-group">
    <%= text_field_tag :apellidouno, params[:apellidouno], class: "form-control-3", placeholder: "primer apellido" %>
  </div>
  <%= submit_tag "Buscar", name: nil, class: "btn btn-primary btn-md" %>
  <%= link_to "Volver", "/estudiantes" , class:"btn btn-secondary"%>
<% end %>


<table class="table table-condensed table-bordered">
  <thead>
  <tr>
    <th>Estudiante</th>
    <th>Rut</th>
    <th>Apoderado</th>
    <th>Nivel Educacional</th>
    <th>Estado</th>
    <th colspan="3">Opciones</th>
  </tr>
  </thead>
  <tbody>
  <% @estudiantes.each do |estudiante| %>
    <tr>
      <td><%= estudiante.nombreuno %> <%= estudiante.apellidouno %></td>
      <td><%= estudiante.rut %></td>
      <td><%= estudiante.user.nombreuno %> <%= estudiante.user.apellidouno%></td>
      <td><%= estudiante.nivel_educacional.descripcion%></td>
      <td>
      <% if estudiante.estado == false %>
      <p class="text-danger"><%= estudiante.estado %></p>
      <% end %>

      <% if estudiante.estado == true %>
      <p class="text-success"><%= estudiante.estado %></p>
      <% end %>

      </td>
      <td><%= link_to 'Mostrar', estudiante_url(estudiante), class: "btn btn-info" %></td>
      <% if can? :editar, estudiante %>
      <td><%= link_to 'Editar', editar_estudiante_url(estudiante), class: "btn btn-warning" %></td>
      <%end%>
      <% if can? :eliminar, estudiante %>
      <% if estudiante.estado == true %>
      <td><%= link_to 'Cambiar estado', estudiante_path(estudiante), class: "btn btn-danger",
                      method: :delete, data: {confirm: '¿Estas seguro?'} %></td>
                      <%end%>
                      <% end %>
    </tr>
    <%end%>

  </tbody>
</table>
<%= will_paginate @estudiantes , renderer: BootstrapPagination::Rails %>
</div>
</body>
</html>

app/views/estudiantes/lista.pdf.erb
<center><h1> Estudiantes de Sala Cuna y Jardín Infantil </h1></center>
<table class="table">
  <thead>
  <tr>
    <th style="width: 200px;">Estudiante</th>
    <th style="width: 200px;">Rut</th>
    <th style="width: 200px;">Apoderado</th>
    <th style="width: 200px;">Nivel Educacional</th>
    <th style="width: 200px;">Jornada</th>
    <th style="width: 200px;">Estado</th>
  </tr>
  </thead>
  <tbody>
  <% @estudiantes.each do |estudiante| %>
  <% if estudiante.estado == true%>
    <tr>
      <td><%= estudiante.nombreuno %> <%= estudiante.apellidouno %></td>
      <td><%= estudiante.rut %></td>
      <td><%= estudiante.user.nombreuno%> <%= estudiante.user.apellidouno%></td>
      <td><%= estudiante.nivel_educacional.descripcion %></td>
      <td><%= estudiante.jornada.descripcion%></td>
      <td><%= estudiante.estado %></td>
    </tr>
    <% end %>
    <%end%>
  </tbody>
</table>

app/views/estudiantes/mostrar.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <meta charset="utf-8">
</head>
<body>
  <div class="container-form">
  <h1>Estudiante: <%= @estudiante.nombreuno %> <%= @estudiante.apellidouno %></h1>
  <h1>Rut: <%= @estudiante.rut %></h1>
  <h1>Fecha de Nacimiento: <%= @estudiante.fecha_nacimiento %></h1>
  <h1>Direccion: <%= @estudiante.direccion %></h1>
  <h1>Comuna: <%= @estudiante.comuna.descripcion %></h1>
  <h1>Nivel Educacional: <%= @estudiante.nivel_educacional.descripcion %></h1>
  <h1>Jornada: <%= @estudiante.jornada.descripcion %></h1>
  <h1>Apoderado: <%= @estudiante.user.nombreuno %> <%= @estudiante.user.apellidouno%></h1>
  <!-- <%= link_to "Generar PDF",estudiante_url(@estudiante, :format => :pdf), class: "btn btn-primary"%> -->
    <a href="/estudiantes" class="btn btn-secondary btn-lg" role="button" aria-pressed="true">Volver</a></h1>
</div>
</body>
</html>

app/views/estudiantes/nuevo.html.erb
<%= render 'formulario' %>

app/views/estudiantes/pdf.pdf.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <meta charset="utf-8">
</head>
<body>
  <img src="https://upload.wikimedia.org/wikipedia/commons/4/43/Logo_UTEM.png" width="150" height="150">
  <center><h1> Estudiante Sala Cuna y Jardin Infantil</h1></center>
  <h1>Nombre: <%= @estudiante.nombreuno %></h1>
  <h1>Apellido: <%= @estudiante.apellidouno %></h1>
  <h1>Rut: <%= @estudiante.rut %></h1>
  <h1>Fecha de Nacimiento: <%= @estudiante.fecha_nacimiento %></h1>
  <h1>Direccion: <%= @estudiante.direccion %></h1>
  <h1>Comuna: <%= @estudiante.comuna.descripcion %></h1>
  <h1>Nivel Educacional: <%= @estudiante.nivel_educacional.descripcion %></h1>
  <h1>Jornada: <%= @estudiante.jornada.descripcion %></h1>
</body>
</html>